# libopenmpt detection
find_library(LIBOPENMPT NAMES openmpt)
if (NOT "${LIBOPENMPT}" STREQUAL "LIBOPENMPT-NOTFOUND")
  add_plugin(libopenmptdecoder)
endif()

# systemd / MPRIS detection
if (NOT ENABLE_MPRIS MATCHES "false")
  find_library(LIB_SYSTEMD NAMES systemd)
  if (NOT LIB_SYSTEMD MATCHES "LIB_SYSTEMD-NOTFOUND")
    message(STATUS "[mpris] systemd found at " ${LIB_SYSTEMD})
    message(STATUS "[mpris] setting ENABLE_MPRIS=true")
    set(ENABLE_MPRIS "true")
  else()
    message(STATUS "[mpris] systemd *not* found. MPRIS plugin not enabled")
    set(ENABLE_MPRIS "false")
  endif()
endif()

if (CMAKE_SYSTEM_NAME MATCHES "Linux")
  add_subdirectory(src/plugins/alsaout)
  add_subdirectory(src/plugins/pulseout)
  if (${ENABLE_PIPEWIRE} MATCHES "true")
    add_plugin(pipewireout)
  endif()
  if (${ENABLE_MPRIS} MATCHES "true")
    add_plugin(mpris)
  endif()
  if (${ENABLE_SNDIO} MATCHES "true")
    add_plugin(sndioout)
  endif()
elseif (CMAKE_SYSTEM_NAME MATCHES "OpenBSD")
  add_subdirectory(src/plugins/sndioout)
  if (${ENABLE_PULSEAUDIO} MATCHES "true")
    add_plugin(pulseout)
  endif()
elseif (CMAKE_SYSTEM_NAME MATCHES "FreeBSD")
  add_subdirectory(src/plugins/sndioout)
  if (${ENABLE_PULSEAUDIO} MATCHES "true")
    add_plugin(pulseout)
  endif()
  if (${ENABLE_ALSA} MATCHES "true")
    add_plugin(alsaout)
  endif()
elseif (CMAKE_SYSTEM_NAME MATCHES "Darwin")
  add_plugin(coreaudioout)
  add_plugin(macosmediakeys)
endif()