macro(add_plugin plugin_dir plugin_name)
    message(STATUS "[add-plugin] adding '${plugin_name}' at path '${plugin_dir}")
    add_subdirectory(${plugin_dir})
    get_property(PLUGIN_DISABLED GLOBAL PROPERTY "DISABLE_${plugin_name}")
    if (NOT PLUGIN_DISABLED STREQUAL "true")
        add_dependencies(musikcube ${plugin_name})
        add_dependencies(musikcubed ${plugin_name})
        add_dependencies(core_c_demo ${plugin_name})
    else()
        message(STATUS "[add-plugin] *** WARNING! *** ${plugin_name} not found.")
    endif()
endmacro(add_plugin)