macro(find_vendor_library target_var library_name)
    find_library(${target_var} NAMES ${library_name} PATHS ${VENDOR_LINK_DIRECTORIES} NO_DEFAULT_PATH NO_CACHE)
    message(STATUS "[find-vendor-library] ${BoldBlue}'${library_name}' library resolved to '${${target_var}}'${ColorReset}")
endmacro(find_vendor_library)

macro(find_library_and_header target_var library_name header_name)
    find_library(${target_var} NAMES ${library_name} NO_CACHE)
    message(STATUS "[find-library-and-header] ${BoldBlue}'${library_name}' library resolved to '${${target_var}}'${ColorReset}")

    find_path(TEMP ${header_name} REQUIRED NO_CACHE)
    if (${TEMP} MATCHES "TEMP-NOTFOUND")
        message(STATUS "[find-library-and-header] ${BoldRed}'${header_name}' COULD NOT BE FOUND!${ColorReset}")
    else()
        message(STATUS "[find-library-and-header] ${BoldBlue}'${header_name}' resolved to '${TEMP}'${ColorReset}")
    endif()
    unset(TEMP)
endmacro(find_library_and_header)
