name: musikcube # you probably want to 'snapcraft register <name>'
version: 0.96.1
summary: a terminal-based music player, metadata indexer, and server
description: |
  musikcube is a fully functional terminal-based music player, library, and
  streaming audio server that runs natively on Windows, macOS, and Linux. It
  also runs well on a Raspberry Pi with a custom DAC (e.g. IQaudIO DAC+,
  HiFiBerry DAC+ and others), and can output 24bit/192k audio comfortably.
grade: stable
confinement: strict
base: core20

parts:
  desktop-glib-musikcube:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only/
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

  musikcube:
    after:
      - desktop-glib-musikcube
    plugin: cmake
    cmake-parameters:
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DENABLE_SNAP=true"
    source: https://github.com/clangen/musikcube.git
    build-packages:
      - build-essential
      - clang
      - cmake
      - libasound2-dev
      - libavformat-dev
      - libavutil-dev
      - libboost-atomic1.71-dev
      - libboost-chrono1.71-dev
      - libboost-date-time1.71-dev
      - libboost-filesystem1.71-dev
      - libboost-system1.71-dev
      - libboost-thread1.71-dev
      - libcurl4-openssl-dev
      - libev-dev
      - libmicrohttpd-dev
      - libmp3lame-dev
      - libncursesw5-dev
      - libogg-dev
      - libpulse-dev
      - libssl-dev
      - libswresample-dev
      - libsystemd-dev
      - libtag1-dev
      - libvorbis-dev
    stage-packages:
      - libasound2
      - libavcodec-extra
      - libavformat58
      - libavutil56
      - libboost-chrono1.71.0
      - libboost-date-time1.71.0
      - libboost-filesystem1.71.0
      - libboost-system1.71.0
      - libboost-thread1.71.0
      - libcurl4
      - libev4
      - libmicrohttpd12
      - libmp3lame0
      - libncursesw5
      - libogg0
      - libpulse0
      - libssl1.1
      - libswresample3
      - libsystemd0
      - libtag1v5
      - libvorbis0a
      - libvorbisfile3

apps:
  app:
    desktop: usr/share/applications/musikcube.snap.desktop
    command: bin/desktop-launch $SNAP/usr/share/musikcube/musikcube
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      ALSA_CONFIG_PATH: /snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa/alsa.conf
      LANG: C.UTF-8
    plugs:
      - home
      - removable-media
      - pulseaudio
      - network
      - network-bind
      - audio-playback
      - alsa
      - desktop
    slots:
      - mpris

  daemon:
    command: bin/desktop-launch $SNAP/usr/share/musikcube/musikcubed
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      ALSA_CONFIG_PATH: /snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa/alsa.conf
      LANG: C.UTF-8
    plugs:
      - home
      - removable-media
      - pulseaudio
      - network
      - network-bind
      - audio-playback
      - alsa
      - desktop
    slots:
      - mpris

layout:
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
